---
name: Build all RPMs
on:
  push:
    branches-ignore:
      - main
  workflow_call:
jobs:
  build:
    name: Build all RPMs in a Fedora container
    runs-on: ubuntu-20.04
    container:
      image: fedora:38
    steps:
      - uses: actions/checkout@v3
      - name: Change directory
        run: cd $GITHUB_WORKSPACE
      - name: Install RPM build dependencies
        run: dnf install -y rpm-build rpmdevtools
      - name: Create the necessary RPM build directories
        run: mkdir -p ~/rpmbuild/SOURCES/
      - name: Install the DNF build dependencies plugin
        run: dnf -y install 'dnf-command(builddep)'
      - name: Build RPMs
        run: |
          # Each RPM spec is stored in its own directory in this repository.
          for pkg in $(ls -d -1 */ | cut -d\/ -f1)
              do cd ${pkg}
              # Copy internal source files.
              cp ./* ~/rpmbuild/SOURCES/
              # Download external source files.
              spectool -g -R *.spec
              # Build the source RPM.
              rpmbuild -bs *.spec
              # Install the required build dependencies.
              dnf builddep -y *.spec
              # Build the binary RPM.
              rpmbuild -bb *.spec
              cd ..
          done
      - name: Install RPMs
        run: dnf -y install ~/rpmbuild/RPMS/*/*.rpm
