---
name: Upload gamingos-scripts source RPM
on:
  push:
    branches:
      - main
    paths:
      - 'gamingos-scripts/**'
jobs:
  build:
    uses: LukeShortCloud/rpm-specs-gaming/.github/workflows/all.yml@main
  upload:
    name: Upload gamingos-scripts source RPM to Fedora Copr
    runs-on: ubuntu-20.04
    container:
      image: fedora:38
    env:
      FEDORA_COPR_LOGIN: ${{ secrets.FEDORA_COPR_LOGIN }}
      FEDORA_COPR_TOKEN: ${{ secrets.FEDORA_COPR_TOKEN }}
    needs:
      - build
    if: ${{ always() && !cancelled() && needs.build.result == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Install RPM build dependencies
        run: dnf install -y copr-cli rpm-build rpmdevtools
      - name: Create the necessary RPM build directories
        run: mkdir -p ~/rpmbuild/SOURCES/
      - name: Copy interal source files
        run: cp ${GITHUB_WORKSPACE}/gamingos-scripts/* ~/rpmbuild/SOURCES/
      - name: Download external source files
        run: spectool -g -R ${GITHUB_WORKSPACE}/gamingos-scripts/*.spec
      - name: Build the source RPM
        run: rpmbuild -bs ${GITHUB_WORKSPACE}/gamingos-scripts/*.spec
      - name: Create the local configuration directory
        run: mkdir ~/.config/
      - name: Create the copr-cli configuration file
        run: |
          cat <<EOF > ~/.config/copr
          [copr-cli]
          login = ${FEDORA_COPR_LOGIN}
          username = ekultails
          token = ${FEDORA_COPR_TOKEN}
          copr_url = https://copr.fedorainfracloud.org
          EOF
      - name: Upload the source RPM to Fedora Copr
        run: copr-cli build gaming ~/rpmbuild/SRPMS/gamingos-scripts-*.src.rpm
